# Generated by Django 5.1.4 on 2025-01-01 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default='', max_length=10, unique=True)),
                ('host', models.CharField(max_length=50, unique=True)),
                ('gust_can_pass', models.BooleanField(default=False)),
                ('vot_to_skip', models.BooleanField(default=1)),
                ('crated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
