# Generated by Django 5.1.4 on 2025-01-01 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='gust_can_pass',
            new_name='guest_can_pass',
        ),
    ]
